name: infra

services:
  auditoria-db:
    extends:
      file: infra/docker-compose.yml
      service: auditoria-db

  code-audit-ai-service:
    extends:
      file: infra/docker-compose.yml
      service: code-audit-ai-service

  backend:
    extends:
      file: infra/docker-compose.yml
      service: backend

  frontend:
    extends:
      file: infra/docker-compose.yml
      service: frontend

volumes:
  sqlserver-data:

networks:
  default:
    name: dev-net
    external: true
