from pydantic import BaseModel, Field, field_validator


class AnalyzeRequest(BaseModel):
    auditId: str = Field(..., description="Audit identifier generated by the Java backend.")
    language: str = Field(..., description="Programming language of the submitted code.")
    code: str = Field(..., description="Source code to analyze.")

    @field_validator("auditId", "language")
    @classmethod
    def required_text_must_not_be_blank(cls, value: str) -> str:
        if not value or not value.strip():
            raise ValueError("This field is required and cannot be blank.")
        return value


class Finding(BaseModel):
    type: str
    severity: str
    title: str
    description: str
    line: int
    suggestion: str


class AnalyzeResponse(BaseModel):
    status: str
    findings: list[Finding]
    pedagogicalExplanation: str
    refactoredCode: str
