from typing import Literal

from pydantic import BaseModel, Field, field_validator


class AnalyzeRequest(BaseModel):
    auditId: str = Field(..., max_length=36, description="Audit identifier generated by the Java backend.")
    language: str = Field(..., max_length=60, description="Programming language of the submitted code.")
    code: str = Field(..., max_length=20000, description="Source code to analyze.")

    @field_validator("auditId", "language")
    @classmethod
    def required_text_must_not_be_blank(cls, value: str) -> str:
        if not value or not value.strip():
            raise ValueError("This field is required and cannot be blank.")
        return value


class Finding(BaseModel):
    type: Literal["security", "syntax", "refactor", "best_practice"]
    severity: Literal["critical", "warning", "suggestion"]
    title: str
    description: str
    line: int | None = None
    suggestion: str | None = None


class AnalyzeResponse(BaseModel):
    auditId: str
    status: Literal["success", "failed"]
    findings: list[Finding]
    pedagogicalExplanation: str
    refactoredCode: str
